### ISSUE TITLE
Installing the plugin

### ISSUE THREAD

**Issue by ebellempire** [matrix-msu/mbira-plugin#1]
Hi, I'm totally new to Kora so please forgive me if this is obvious. I successfully installed Kora and copied the contents of this repo into a folder called `mbira` (so I have for example a file at `/path/to/kora/plugins/mbira/index.php`). At first I received an error when activating mbira saying that the file `pluginsConfig.php` was not found so I renamed `pluginsConfig.php.dist` (removing the `dist` part). I entered database credentials in that file but it doesn't seem to have any impact. 

I get errors on all the mbira-related pages within Kora. For example, the following when clicking on Mbira > Projects:

```
Warning: require_once(includes/conf.php): failed to open stream: No such file or directory in /path/to/kora/plugins/pluginsInclude.php on line 40
Fatal error: require_once(): Failed opening required 'includes/conf.php' (include_path='.:/usr/local/share/pear54') in /path/to/kora/plugins/pluginsInclude.php on line 40
```

Again, I suspect this is because I don't really know much about Kora, but any help would be greatly appreciated. This looks like a really promising project and I'd love to get it running on my own server so I can really dig in to how it works.

Thanks -- Erin

**Comment by bogderp** [comment]
I believe you need to give the plugin 755 permissions

**Comment by seilagonzalez** [comment]
inside of the pluginConfig file there you have to include kora url and path like this:

define('baseUrlPlugin','http://dev2.matrix.msu.edu/~seila.gonzalez/kora/');
define('basePathPlugin','/matrix/home/seila.gonzalez/public_html/kora/‘);

Seila

On Jan 5, 2016, at 10:08 PM, Erin Bell <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi, I'm totally new to Kora so please forgive me if this is obvious. I successfully installed Kora and copied the contents of this repo into a folder called mbira (so I have for example a file at /path/to/kora/plugins/mbira/index.php). At first I received an error when activating mbira saying that the file pluginsConfig.php was not found so I renamed pluginsConfig.php.dist (removing the dist part). I entered database credentials in that file but it doesn't seem to have any impact.

I get errors on all the mbira-related pages within Kora. For example, the following when clicking on Mbria > Projects:

Warning: require_once(includes/conf.php): failed to open stream: No such file or directory in /path/to/kora/plugins/pluginsInclude.php on line 40
Fatal error: require_once(): Failed opening required 'includes/conf.php' (include_path='.:/usr/local/share/pear54') in /path/to/kora/plugins/pluginsInclude.php on line 40

Again, I suspect this is because I don't really know much about Kora, but any help would be greatly appreciated. This looks like a really promising project and I'd love to get it running on my own server so I can really dig in to how it works.

Thanks -- Erin

**Comment by watrall** [comment]
Erin - its also worth mentioning that the mbira authroing plugin is still very much an alpha.  It isn't feature complete and probably has stray bugs.  However, we're on track to get the a sold public beta released (as well as the finished front end web template) done in 5-6 months or so.
